### ISSUE TITLE
Source map console warnings

### ISSUE THREAD

**Issue by livwvil** [alexey-koran/react-template#10]
https://github.com/alexey-koren/bundlers-boilerplates/blob/95332b2ec6ea9f09c85c7563c7c35865cef63ff5/webpack.config.ts#L43
``` devtool: isProduction ? 'source-map' : 'eval-source-map'``` helps to avoid chrome console warnings
https://stackoverflow.com/questions/61767538/devtools-failed-to-load-sourcemap-for-webpack-node-modules-js-map-http-e

**Comment by alexey-koran** [comment]
> https://github.com/alexey-koren/bundlers-boilerplates/blob/95332b2ec6ea9f09c85c7563c7c35865cef63ff5/webpack.config.ts#L43 ` devtool: isProduction ? 'source-map' : 'eval-source-map'` helps to avoid chrome console warnings https://stackoverflow.com/questions/61767538/devtools-failed-to-load-sourcemap-for-webpack-node-modules-js-map-http-e

According to the devtool option table https://webpack.js.org/configuration/devtool/#root
eval-source-map property is not the better choice due to the build time performance

Should look into other solutions
