### ISSUE TITLE
ESlint fragments

### ISSUE THREAD

**Issue by livwvil** [alexey-koran/react-template#11]
https://github.com/alexey-koren/bundlers-boilerplates/blob/95332b2ec6ea9f09c85c7563c7c35865cef63ff5/.eslintrc#L186
Maybe this is better ```    "react/jsx-fragments" : ["error", "syntax"]```
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md

**Comment by alexey-koran** [comment]
> https://github.com/alexey-koren/bundlers-boilerplates/blob/95332b2ec6ea9f09c85c7563c7c35865cef63ff5/.eslintrc#L186 Maybe this is better ` "react/jsx-fragments" : ["error", "syntax"]` https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md

Sure. [Fixed](https://github.com/alexey-koran/bundlers-boilerplates/commit/419ab870b3eb29935a0177198483ce28a7cf9a19)
