### ISSUE TITLE
Static files unreachable during develop

### ISSUE THREAD

**Issue by livwvil** [alexey-koran/react-template#8]
https://github.com/alexey-koren/bundlers-boilerplates/blob/95332b2ec6ea9f09c85c7563c7c35865cef63ff5/webpack.config.ts#L108
It seems you should fix "static" to "src/static"

**Comment by alexey-koran** [comment]
https://github.com/alexey-koran/bundlers-boilerplates/commit/c2d237bf87b005e5a95eb6a5c9f9a1f0e3a2ac95
