### ISSUE TITLE
Is it duplication?

### ISSUE THREAD

**Issue by livwvil** [alexey-koran/react-template#9]
https://github.com/alexey-koren/bundlers-boilerplates/blob/95332b2ec6ea9f09c85c7563c7c35865cef63ff5/webpack.config.ts#L52-L61

**Comment by alexey-koran** [comment]
> https://github.com/alexey-koren/bundlers-boilerplates/blob/95332b2ec6ea9f09c85c7563c7c35865cef63ff5/webpack.config.ts#L52-L61

No. You can read about it more here https://blog.logrocket.com/babel-vs-typescript/
But I will change babel-loader to https://github.com/TypeStrong/fork-ts-checker-webpack-plugin
And I'll check how it will look
